/* Constants */
/* Status codes */
export const WWPASS_OK_MSG = 'OK';
export const WWPASS_STATUS = {
  CONTINUE: 100,
  OK: 200,
  INTERNAL_ERROR: 400,
  ALREADY_PERSONALIZED: 401,
  PASSWORD_MISMATCH: 402,
  PASSWORD_LOCKOUT: 403,
  WRONG_KEY: 404,
  WRONG_KEY_SECOND: 405,
  NOT_A_KEY: 406,
  NOT_A_KEY_SECOND: 407,
  KEY_DISABLED: 408,
  NOT_ALLOWED: 409,
  BLANK_TOKEN: 410,
  BLANK_SECOND_TOKEN: 411,
  ACTIVITY_PROFILE_LOCKED: 412,
  SSL_REQUIRED: 413,
  BLANK_NORMAL_TOKEN: 414,
  BLANK_SECOND_NORMAL_TOKEN: 415,
  BLANK_MASTER_TOKEN: 416,
  BLANK_SECOND_MASTER_TOKEN: 417,
  NOT_ACTIVATED_TOKEN: 418,
  NOT_ACTIVATED_SECOND_TOKEN: 419,
  WRONG_KEY_SET: 420,
  NO_VERIFIER: 421,
  INCOMPLETE_KEYSET: 422,
  INVALID_TICKET: 423,
  SAME_TOKEN: 424,
  NO_RECOVERY_INFO: 425,
  BAD_RECOVERY_REQUEST: 426,
  RECOVERY_FAILED: 427,

  TERMINAL_ERROR: 500,
  TERMINAL_NOT_FOUND: 501,
  TERMINAL_BAD_REQUEST: 502,
  NO_CONNECTION: 503,
  NETWORK_ERROR: 504,
  PROTOCOL_ERROR: 505,
  UNKNOWN_HANDLER: 506,
  TERMINAL_CANCELED: 590,

  TIMEOUT: 600,
  TICKET_TIMEOUT: 601,
  USER_REJECT: 603,

  NO_AUTH_INTERFACES_FOUND: 604,
  TERMINAL_TIMEOUT: 605,
  UNSUPPORTED_PLATFORM: 606
};

export const WWPASS_NO_AUTH_INTERFACES_FOUND_MSG = 'No WWPass SecurityPack is found on your computer or WWPass Browser Plugin is disabled';
export const WWPASS_UNSUPPORTED_PLATFORM_MSG_TMPL = 'WWPass authentication is not supported on';

/* end of status codes */

export const WWPASS_KEY_TYPE_ANY = '';
export const WWPASS_KEY_TYPE_PASSKEY = 'passkey';
export const WWPASS_KEY_TYPE_SERVICE = 'service';
export const WWPASS_KEY_TYPE_BLANK = 'blank';
export const WWPASS_KEY_TYPE_BLANKPASSKEY = 'blankpasskey';
export const WWPASS_KEY_TYPE_BLANKSERVICE = 'blankservice';
export const WWPASS_KEY_TYPE_BLANK2NDSERVICE = 'blank2ndservice';
export const WWPASS_KEY_TYPE_DEFAULT = WWPASS_KEY_TYPE_PASSKEY;
